# Uncomment the next line to define a global platform for your project
# platform :ios, '10.2'

target 'signLanguage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for signLanguage
 pod 'Firebase/Analytics', '6.19.0'
end
